### ISSUE TITLE
Rest API to Authentication and Request other service

### ISSUE THREAD

**Issue by deepakshrma** [oracle/bmcs-java-sdk#10]
Hi,
We are trying to build some generic tool around all providers including Oracle. For this, We need some common methodology and implementation. We are looking for something like OAuth, via which we can login to oracle bmc. And can get authorization header for next request.

https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/apiref.htm
https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/sdks.htm
I was looking for REST API doc. But I did not find sample data for authorization. What I can see only SDK implementation. Please let me know in case of any reference to APIs.

**Comment by priteshkp** [comment]
Hey Deepak,
   Oracle Bare Metal Cloud Services do not support other types of authentication right now.  The only API access allowed is through API keys:
https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/usercredentials.htm#two

This may change at a later date, but right now that is the only way.  Console access can use federation though:
https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Concepts/federation.htm

Thanks,
Pritesh

**Comment by deepakshrma** [comment]
@priteshkp :+1: 
Yes, I went through documents, I got to know that Internally sdk uses rest API to call with Authorization Header. However, I feel that documentation part is not very much clear. Anyways, we are building tool with SDK now. We can sync-up later if we needed any help.
